-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  parent_account_id uuid,
  name text NOT NULL,
  website text,
  industry text,
  phone text,
  email text,
  address jsonb DEFAULT '{}'::jsonb,
  annual_revenue numeric,
  employee_count integer,
  description text,
  notes text,
  assigned_to uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  custom_fields jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT accounts_parent_account_id_fkey FOREIGN KEY (parent_account_id) REFERENCES public.accounts(id),
  CONSTRAINT accounts_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT accounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  lead_id uuid,
  user_id uuid,
  type text NOT NULL,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  subject text,
  activity_type text,
  scheduled_at timestamp with time zone,
  completed_at timestamp with time zone,
  is_completed boolean DEFAULT false,
  duration_minutes integer,
  outcome text,
  updated_at timestamp with time zone DEFAULT now(),
  account_id uuid,
  contact_id uuid,
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT activities_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT activities_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT activities_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.activity_score_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  company_id uuid NOT NULL,
  activity_id uuid,
  rule_id uuid,
  points integer NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_score_events_pkey PRIMARY KEY (id),
  CONSTRAINT activity_score_events_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT activity_score_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT activity_score_events_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id),
  CONSTRAINT activity_score_events_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.scoring_rules(id)
);
CREATE TABLE public.api_client_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  api_client_id uuid NOT NULL,
  endpoint text NOT NULL,
  method text NOT NULL,
  status_code integer,
  response_time_ms integer,
  ip_address text,
  user_agent text,
  request_body jsonb,
  error_message text,
  lead_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_client_requests_pkey PRIMARY KEY (id),
  CONSTRAINT api_client_requests_api_client_id_fkey FOREIGN KEY (api_client_id) REFERENCES public.api_clients(id),
  CONSTRAINT api_client_requests_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.api_clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  client_name text NOT NULL,
  api_key text NOT NULL UNIQUE,
  api_secret_hash text NOT NULL,
  is_active boolean DEFAULT true,
  rate_limit integer DEFAULT 100,
  allowed_origins ARRAY,
  webhook_url text,
  custom_field_mapping jsonb DEFAULT '{}'::jsonb,
  default_lead_source text DEFAULT 'api'::text,
  default_assigned_to uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  last_used_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_clients_pkey PRIMARY KEY (id),
  CONSTRAINT api_clients_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT api_clients_default_assigned_to_fkey FOREIGN KEY (default_assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT api_clients_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.assignment_round_robin_state (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  user_id uuid NOT NULL,
  last_assigned_at timestamp with time zone DEFAULT now(),
  assignment_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT assignment_round_robin_state_pkey PRIMARY KEY (id),
  CONSTRAINT assignment_round_robin_state_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT assignment_round_robin_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  actor_id uuid,
  actor_email text NOT NULL,
  actor_role USER-DEFINED NOT NULL,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  user_agent text,
  is_impersonation boolean DEFAULT false,
  impersonated_user_id uuid,
  severity text DEFAULT 'info'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.automation_rules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  trigger jsonb NOT NULL,
  conditions jsonb,
  actions jsonb NOT NULL,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 10,
  run_once_per_lead boolean DEFAULT false,
  max_runs_per_day integer,
  stats jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT automation_rules_pkey PRIMARY KEY (id),
  CONSTRAINT automation_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT automation_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.automation_runs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  automation_rule_id uuid NOT NULL,
  company_id uuid NOT NULL,
  lead_id uuid,
  status text NOT NULL DEFAULT 'pending'::text,
  trigger_data jsonb,
  conditions_met boolean,
  actions_executed jsonb DEFAULT '[]'::jsonb,
  error_message text,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT automation_runs_pkey PRIMARY KEY (id),
  CONSTRAINT automation_runs_automation_rule_id_fkey FOREIGN KEY (automation_rule_id) REFERENCES public.automation_rules(id),
  CONSTRAINT automation_runs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT automation_runs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.chatbot_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  session_id text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['system'::text, 'user'::text, 'assistant'::text])),
  content text NOT NULL,
  tool_calls jsonb DEFAULT '[]'::jsonb,
  tool_results jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chatbot_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT chatbot_conversations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  company_slug text UNIQUE,
  plan text DEFAULT 'starter'::text,
  status text DEFAULT 'active'::text,
  settings jsonb DEFAULT '{}'::jsonb,
  logo_url text,
  industry_type text,
  size text,
  country text,
  timezone text DEFAULT 'UTC'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  account_id uuid,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  phone text,
  mobile_phone text,
  title text,
  department text,
  linkedin_url text,
  twitter_handle text,
  preferred_contact_method text CHECK (preferred_contact_method = ANY (ARRAY['email'::text, 'phone'::text, 'mobile'::text, 'linkedin'::text])),
  do_not_call boolean DEFAULT false,
  do_not_email boolean DEFAULT false,
  address jsonb DEFAULT '{}'::jsonb,
  is_primary boolean DEFAULT false,
  is_decision_maker boolean DEFAULT false,
  reporting_to uuid,
  last_contacted_at timestamp with time zone,
  last_activity_at timestamp with time zone,
  notes text,
  description text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'bounced'::text, 'unsubscribed'::text, 'archived'::text])),
  lifecycle_stage text CHECK (lifecycle_stage = ANY (ARRAY['lead'::text, 'marketing_qualified'::text, 'sales_qualified'::text, 'opportunity'::text, 'customer'::text, 'evangelist'::text])),
  assigned_to uuid,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT contacts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT contacts_reporting_to_fkey FOREIGN KEY (reporting_to) REFERENCES public.contacts(id),
  CONSTRAINT contacts_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.custom_field_audit (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  custom_field_id uuid,
  company_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['created'::text, 'updated'::text, 'deleted'::text, 'activated'::text, 'deactivated'::text])),
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  ip_address text,
  user_agent text,
  CONSTRAINT custom_field_audit_pkey PRIMARY KEY (id),
  CONSTRAINT custom_field_audit_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT custom_field_audit_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.user_profiles(id),
  CONSTRAINT custom_field_audit_custom_field_id_fkey FOREIGN KEY (custom_field_id) REFERENCES public.custom_field_definitions(id)
);
CREATE TABLE public.custom_field_definitions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  field_name text NOT NULL,
  field_label text NOT NULL,
  field_description text,
  entity_type USER-DEFINED NOT NULL,
  data_type USER-DEFINED NOT NULL,
  is_required boolean DEFAULT false,
  is_unique boolean DEFAULT false,
  is_searchable boolean DEFAULT true,
  field_options jsonb DEFAULT '[]'::jsonb,
  validation_rules jsonb DEFAULT '{}'::jsonb,
  display_order integer DEFAULT 0,
  placeholder text,
  help_text text,
  default_value text,
  is_active boolean DEFAULT true,
  is_system_field boolean DEFAULT false,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT custom_field_definitions_pkey PRIMARY KEY (id),
  CONSTRAINT custom_field_definitions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT custom_field_definitions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT custom_field_definitions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.email_sequences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  json_definition jsonb NOT NULL,
  entry_conditions jsonb,
  exit_on_reply boolean DEFAULT true,
  exit_on_goal jsonb,
  is_active boolean DEFAULT false,
  send_time_window jsonb,
  max_emails_per_day integer DEFAULT 3,
  stats jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_sequences_pkey PRIMARY KEY (id),
  CONSTRAINT email_sequences_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT email_sequences_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.email_suppression_list (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  email text NOT NULL,
  reason text NOT NULL CHECK (reason = ANY (ARRAY['unsubscribed'::text, 'bounced'::text, 'spam_complaint'::text, 'manual'::text])),
  source text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_suppression_list_pkey PRIMARY KEY (id),
  CONSTRAINT email_suppression_list_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.email_template_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_id uuid NOT NULL,
  version_number integer NOT NULL DEFAULT 1,
  editor_type text NOT NULL CHECK (editor_type = ANY (ARRAY['code'::text, 'dragdrop'::text, 'html'::text])),
  subject text NOT NULL,
  from_name text,
  from_email text,
  reply_to text,
  mjml text,
  html text NOT NULL,
  text_version text,
  json_design jsonb,
  variables jsonb DEFAULT '[]'::jsonb,
  is_published boolean DEFAULT false,
  published_at timestamp with time zone,
  preview_data jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_template_versions_pkey PRIMARY KEY (id),
  CONSTRAINT email_template_versions_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.email_templates(id),
  CONSTRAINT email_template_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  folder text DEFAULT 'general'::text,
  category text,
  is_active boolean DEFAULT true,
  is_shared boolean DEFAULT false,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT email_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.import_configs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  schema_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  duplicate_policy_default text NOT NULL DEFAULT 'skip'::text,
  version integer NOT NULL DEFAULT 1,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT import_configs_pkey PRIMARY KEY (id),
  CONSTRAINT import_configs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT import_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT import_configs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.import_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  filename text NOT NULL,
  total_records integer DEFAULT 0,
  successful_records integer DEFAULT 0,
  failed_records integer DEFAULT 0,
  status text DEFAULT 'processing'::text,
  error_details jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  mode text NOT NULL DEFAULT 'apply'::text,
  duplicate_policy text,
  config_version integer,
  validation_errors jsonb,
  validation_warnings jsonb,
  summary jsonb,
  error_report_url text,
  CONSTRAINT import_history_pkey PRIMARY KEY (id),
  CONSTRAINT import_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT import_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.import_mappings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  source_key text NOT NULL,
  mapping_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  updated_by uuid,
  usage_count integer NOT NULL DEFAULT 0,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT import_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT import_mappings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT import_mappings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT import_mappings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.import_telemetry (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  user_id uuid,
  phase text NOT NULL CHECK (phase = ANY (ARRAY['dry_run'::text, 'import'::text])),
  stats jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_count integer NOT NULL DEFAULT 0,
  warning_count integer NOT NULL DEFAULT 0,
  duplicate_policy text,
  config_version integer,
  duration_ms integer,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT import_telemetry_pkey PRIMARY KEY (id),
  CONSTRAINT import_telemetry_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT import_telemetry_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.integration_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['email'::text, 'slack'::text, 'sms'::text, 'webhook'::text])),
  provider text NOT NULL,
  config jsonb NOT NULL,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT integration_settings_pkey PRIMARY KEY (id),
  CONSTRAINT integration_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT integration_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.lead_assignment_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  previous_assigned_to uuid,
  new_assigned_to uuid,
  assigned_by uuid,
  assignment_reason text,
  assignment_source text CHECK (assignment_source = ANY (ARRAY['manual'::text, 'auto'::text, 'rule'::text])),
  assignment_rule_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_assignment_history_pkey PRIMARY KEY (id),
  CONSTRAINT lead_assignment_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_assignment_history_previous_assigned_to_fkey FOREIGN KEY (previous_assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT lead_assignment_history_new_assigned_to_fkey FOREIGN KEY (new_assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT lead_assignment_history_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.user_profiles(id),
  CONSTRAINT lead_assignment_history_assignment_rule_id_fkey FOREIGN KEY (assignment_rule_id) REFERENCES public.lead_assignment_rules(id)
);
CREATE TABLE public.lead_assignment_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  conditions jsonb NOT NULL DEFAULT '{}'::jsonb,
  assignment_type text NOT NULL DEFAULT 'round_robin'::text,
  assigned_to uuid,
  is_active boolean NOT NULL DEFAULT true,
  priority integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_assignment_rules_pkey PRIMARY KEY (id),
  CONSTRAINT lead_assignment_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT lead_assignment_rules_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.lead_contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  company_id uuid NOT NULL,
  is_primary boolean DEFAULT false,
  role text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT lead_contacts_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_contacts_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT lead_contacts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT lead_contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.lead_picklist_options (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['source'::text, 'status'::text, 'priority'::text, 'category'::text, 'industry'::text, 'custom'::text])),
  value text NOT NULL,
  label text NOT NULL,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  CONSTRAINT lead_picklist_options_pkey PRIMARY KEY (id),
  CONSTRAINT lead_picklist_options_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT lead_picklist_options_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.lead_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL UNIQUE,
  company_id uuid NOT NULL,
  current_score integer NOT NULL DEFAULT 0 CHECK (current_score >= 0 AND current_score <= 100),
  last_calculated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_scores_pkey PRIMARY KEY (id),
  CONSTRAINT lead_scores_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_scores_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  assigned_to uuid,
  pipeline_stage_id uuid,
  name text NOT NULL,
  email text,
  phone text,
  company text,
  title text,
  source text,
  status text DEFAULT 'new'::text,
  deal_value numeric,
  expected_close_date timestamp with time zone,
  notes text,
  priority text DEFAULT 'medium'::text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  assigned_at timestamp with time zone,
  assignment_source text DEFAULT 'manual'::text,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  lead_source text,
  industry text,
  location text,
  lead_score integer DEFAULT 0,
  last_contact_date timestamp with time zone,
  assignment_rule_id uuid,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  account_id uuid,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT leads_pipeline_stage_id_fkey FOREIGN KEY (pipeline_stage_id) REFERENCES public.pipeline_stages(id),
  CONSTRAINT leads_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT leads_assignment_rule_id_fkey FOREIGN KEY (assignment_rule_id) REFERENCES public.lead_assignment_rules(id),
  CONSTRAINT leads_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.outbound_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  lead_id uuid,
  template_id uuid,
  template_version_id uuid,
  to_email text NOT NULL,
  to_name text,
  subject text NOT NULL,
  html text NOT NULL,
  text_version text,
  provider text,
  provider_message_id text,
  status text NOT NULL DEFAULT 'queued'::text,
  error_message text,
  metrics jsonb DEFAULT '{}'::jsonb,
  sequence_id uuid,
  enrollment_id uuid,
  automation_rule_id uuid,
  context jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT outbound_messages_pkey PRIMARY KEY (id),
  CONSTRAINT outbound_messages_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT outbound_messages_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT outbound_messages_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.email_templates(id),
  CONSTRAINT outbound_messages_template_version_id_fkey FOREIGN KEY (template_version_id) REFERENCES public.email_template_versions(id),
  CONSTRAINT outbound_messages_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.pipeline_stages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  color text DEFAULT '#3B82F6'::text,
  order_position integer NOT NULL,
  is_active boolean DEFAULT true,
  is_closed_won boolean DEFAULT false,
  is_closed_lost boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pipeline_stages_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_stages_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.role_permissions (
  role USER-DEFINED NOT NULL,
  permissions ARRAY NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role)
);
CREATE TABLE public.scoring_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  rule_type text NOT NULL CHECK (rule_type = ANY (ARRAY['activity'::text, 'field'::text, 'engagement'::text])),
  activity_type text,
  field_name text,
  condition_operator text,
  condition_value text,
  score_value integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scoring_rules_pkey PRIMARY KEY (id),
  CONSTRAINT scoring_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.sequence_enrollments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sequence_id uuid NOT NULL,
  lead_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  current_step integer DEFAULT 0,
  next_run_at timestamp with time zone,
  steps_completed integer DEFAULT 0,
  emails_sent integer DEFAULT 0,
  last_email_sent_at timestamp with time zone,
  exit_reason text,
  exited_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  enrolled_by uuid,
  enrolled_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sequence_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT sequence_enrollments_sequence_id_fkey FOREIGN KEY (sequence_id) REFERENCES public.email_sequences(id),
  CONSTRAINT sequence_enrollments_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT sequence_enrollments_enrolled_by_fkey FOREIGN KEY (enrolled_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  lead_id uuid,
  assigned_to uuid,
  title text NOT NULL,
  description text,
  status text DEFAULT 'pending'::text,
  priority text DEFAULT 'medium'::text,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  account_id uuid,
  contact_id uuid,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT tasks_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT tasks_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.user_preferences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  theme text DEFAULT 'light'::text CHECK (theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])),
  items_per_page integer DEFAULT 20 CHECK (items_per_page >= 10 AND items_per_page <= 100),
  default_view text DEFAULT 'list'::text CHECK (default_view = ANY (ARRAY['list'::text, 'grid'::text, 'kanban'::text])),
  dashboard_widgets jsonb DEFAULT '{"show_tasks": true, "show_pipeline": true, "show_activities": true, "show_recent_leads": true}'::jsonb,
  email_notifications boolean DEFAULT true,
  email_lead_assigned boolean DEFAULT true,
  email_lead_updated boolean DEFAULT false,
  email_task_assigned boolean DEFAULT true,
  email_task_due boolean DEFAULT true,
  email_daily_digest boolean DEFAULT false,
  email_weekly_digest boolean DEFAULT false,
  in_app_notifications boolean DEFAULT true,
  date_format text DEFAULT 'MM/DD/YYYY'::text CHECK (date_format = ANY (ARRAY['MM/DD/YYYY'::text, 'DD/MM/YYYY'::text, 'YYYY-MM-DD'::text])),
  time_format text DEFAULT '12h'::text CHECK (time_format = ANY (ARRAY['12h'::text, '24h'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  role USER-DEFINED DEFAULT 'sales_rep'::user_role,
  first_name text,
  last_name text,
  avatar_url text,
  phone text,
  title text,
  department text,
  settings jsonb DEFAULT '{}'::jsonb,
  permissions jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  timezone text DEFAULT 'UTC'::text,
  language text DEFAULT 'en'::text,
  onboarding_completed boolean DEFAULT false,
  onboarding_steps jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.workflow_template_packs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  industry text NOT NULL,
  icon_url text,
  preview_image_url text,
  tags ARRAY,
  template_ids ARRAY DEFAULT ARRAY[]::uuid[],
  download_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_template_packs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflow_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  description text,
  json_definition jsonb NOT NULL,
  category text,
  industry text,
  tags ARRAY,
  entry_conditions jsonb,
  exit_on_reply boolean DEFAULT true,
  exit_on_goal jsonb,
  send_time_window jsonb,
  max_emails_per_day integer DEFAULT 3,
  is_public boolean DEFAULT false,
  is_active boolean DEFAULT true,
  usage_count integer DEFAULT 0,
  last_used_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_templates_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT workflow_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);