import { useState } from 'react';
import emailService from '../services/emailService';
import toast from 'react-hot-toast';
import {
  SparklesIcon,
  LightBulbIcon,
  RocketLaunchIcon,
  BeakerIcon
} from '@heroicons/react/24/outline';

/**
 * AI Toolbar Component for Email Template Editor
 * Provides AI-powered features for template creation and optimization
 */
const EmailAiToolbar = ({ 
  templateData, 
  setTemplateData, 
  mjmlContent, 
  setMjmlContent, 
  htmlContent,
  editorMode,
  onInsertVisualHtml
}) => {
  const [loading, setLoading] = useState(false);
  const [showAiPanel, setShowAiPanel] = useState(false);
  const [aiMode, setAiMode] = useState(null); // 'generate', 'optimize', 'suggest', 'variants'
  
  // AI Generation State
  const [generateDescription, setGenerateDescription] = useState('');
  const [generateType, setGenerateType] = useState('general');
  const [generateContext, setGenerateContext] = useState({
    tone: 'professional',
    industry: 'General B2B'
  });

  // Subject Variants State
  const [subjectVariants, setSubjectVariants] = useState([]);

  // Optimization State
  const [optimizationGoals, setOptimizationGoals] = useState(['engagement', 'clarity']);

  // Personalization Suggestions State
  const [personalizationSuggestions, setPersonalizationSuggestions] = useState([]);

  const handleGenerateTemplate = async () => {
    if (!generateDescription.trim()) {
      toast.error('Please describe what you want to create');
      return;
    }

    try {
      setLoading(true);
      const response = await emailService.aiGenerateTemplate(
        generateDescription,
        generateType,
        generateContext
      );

      const result = response.data;
      
      // Update template data
      setTemplateData(prev => ({
        ...prev,
        subject: result.subject || prev.subject,
        description: result.description || prev.description,
        folder: result.suggested_folder || prev.folder
      }));

      // Update MJML or insert into visual editor
      if (result.html) {
        if (typeof onInsertVisualHtml === 'function') {
          onInsertVisualHtml(result.html, result.subject);
        } else {
          const mjml = wrapHtmlInMjml(result.html, result.subject);
          setMjmlContent(mjml);
        }
      }

      toast.success('✨ Template generated by AI!');
      setShowAiPanel(false);
      setAiMode(null);
      setGenerateDescription('');
    } catch (error) {
      console.error('Error generating template:', error);
      toast.error(error.response?.data?.message || 'Failed to generate template');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateSubjectVariants = async () => {
    if (!templateData.subject) {
      toast.error('Please enter a subject line first');
      return;
    }

    try {
      setLoading(true);
      const response = await emailService.aiGenerateSubjectVariants(
        templateData.subject,
        null,
        5
      );

      setSubjectVariants(response.data);
      toast.success('Generated 5 subject line variants!');
    } catch (error) {
      console.error('Error generating variants:', error);
      toast.error('Failed to generate subject variants');
    } finally {
      setLoading(false);
    }
  };

  const handleOptimizeContent = async () => {
    if (!htmlContent && !mjmlContent) {
      toast.error('Please create some content first');
      return;
    }

    try {
      setLoading(true);
      const response = await emailService.aiOptimizeContent(
        htmlContent || mjmlContent,
        templateData.subject,
        optimizationGoals
      );

      const result = response.data;
      
      // Update subject if improved
      if (result.improved_subject) {
        setTemplateData(prev => ({
          ...prev,
          subject: result.improved_subject
        }));
      }

      // Update HTML/MJML if improved
      if (result.improved_html) {
        if (typeof onInsertVisualHtml === 'function') {
          onInsertVisualHtml(result.improved_html, result.improved_subject || templateData.subject);
        } else {
          const mjml = wrapHtmlInMjml(result.improved_html, result.improved_subject);
          setMjmlContent(mjml);
        }
      }

      // Show recommendations
      if (result.improvements_made && result.improvements_made.length > 0) {
        toast.success(
          `✨ Optimized! Improvements: ${result.improvements_made.slice(0, 2).join(', ')}`,
          { duration: 5000 }
        );
      } else {
        toast.success('Content optimized!');
      }
    } catch (error) {
      console.error('Error optimizing content:', error);
      toast.error('Failed to optimize content');
    } finally {
      setLoading(false);
    }
  };

  const handleSuggestPersonalization = async () => {
    if (!htmlContent && !mjmlContent) {
      toast.error('Please create some content first');
      return;
    }

    try {
      setLoading(true);
      const response = await emailService.aiSuggestVariables(
        htmlContent || mjmlContent,
        templateData.description || ''
      );

      setPersonalizationSuggestions(response.data);
      toast.success(`Found ${response.data.length} personalization suggestions!`);
    } catch (error) {
      console.error('Error suggesting personalization:', error);
      toast.error('Failed to get suggestions');
    } finally {
      setLoading(false);
    }
  };

  const wrapHtmlInMjml = (html, subject = '') => {
    // Simple wrapper - this is a basic approach
    // In production, you might want a more sophisticated HTML to MJML converter
    return `<mjml>
  <mj-head>
    <mj-title>${subject || 'Email Template'}</mj-title>
    <mj-preview>${subject || 'Preview text'}</mj-preview>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        ${html}
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`;
  };

  const applySubjectVariant = (variant) => {
    setTemplateData(prev => ({
      ...prev,
      subject: variant.subject
    }));
    toast.success('Subject line applied!');
  };

  return (
    <div className="relative">
      {/* AI Toggle Button */}
      <button
        onClick={() => setShowAiPanel(!showAiPanel)}
        className={`btn-primary flex items-center space-x-2 ${showAiPanel ? 'ring-2 ring-purple-500' : ''}`}
        title="AI Assistant"
      >
        <SparklesIcon className="h-5 w-5" />
        <span>AI Assistant</span>
      </button>

      {/* AI Panel */}
      {showAiPanel && (
        <div className="absolute right-0 mt-2 w-96 bg-white rounded-lg shadow-xl border-2 border-purple-200 z-50">
          <div className="p-4 border-b border-gray-200 bg-gradient-to-r from-purple-50 to-blue-50">
            <h3 className="font-semibold text-gray-900 flex items-center">
              <SparklesIcon className="h-5 w-5 mr-2 text-purple-600" />
              AI Email Assistant
            </h3>
            <p className="text-xs text-gray-600 mt-1">
              Let AI help you create amazing emails
            </p>
          </div>

          <div className="p-4 space-y-3">
            {/* AI Action Buttons */}
            {!aiMode && (
              <div className="space-y-2">
                <button
                  onClick={() => setAiMode('generate')}
                  className="w-full btn-secondary justify-start text-left"
                >
                  <RocketLaunchIcon className="h-5 w-5 mr-2 text-purple-600" />
                  <div>
                    <div className="font-medium">Generate Template</div>
                    <div className="text-xs text-gray-600">Create from description</div>
                  </div>
                </button>

                <button
                  onClick={() => {
                    setAiMode('variants');
                    handleGenerateSubjectVariants();
                  }}
                  disabled={!templateData.subject || loading}
                  className="w-full btn-secondary justify-start text-left"
                >
                  <BeakerIcon className="h-5 w-5 mr-2 text-blue-600" />
                  <div>
                    <div className="font-medium">Subject Variants</div>
                    <div className="text-xs text-gray-600">Generate A/B test options</div>
                  </div>
                </button>

                <button
                  onClick={() => {
                    setAiMode('optimize');
                    handleOptimizeContent();
                  }}
                  disabled={(!htmlContent && !mjmlContent) || loading}
                  className="w-full btn-secondary justify-start text-left"
                >
                  <SparklesIcon className="h-5 w-5 mr-2 text-green-600" />
                  <div>
                    <div className="font-medium">Optimize Content</div>
                    <div className="text-xs text-gray-600">Improve engagement</div>
                  </div>
                </button>

                <button
                  onClick={() => {
                    setAiMode('suggest');
                    handleSuggestPersonalization();
                  }}
                  disabled={(!htmlContent && !mjmlContent) || loading}
                  className="w-full btn-secondary justify-start text-left"
                >
                  <LightBulbIcon className="h-5 w-5 mr-2 text-yellow-600" />
                  <div>
                    <div className="font-medium">Personalization Tips</div>
                    <div className="text-xs text-gray-600">Suggest variables</div>
                  </div>
                </button>
              </div>
            )}

            {/* Generate Template Form */}
            {aiMode === 'generate' && (
              <div className="space-y-3">
                <button
                  onClick={() => setAiMode(null)}
                  className="text-sm text-gray-600 hover:text-gray-900"
                >
                  ← Back
                </button>

                <textarea
                  placeholder="Describe the email you want to create... (e.g., 'Welcome email for new customers with company intro and CTA to schedule demo')"
                  value={generateDescription}
                  onChange={(e) => setGenerateDescription(e.target.value)}
                  className="input w-full h-24 text-sm"
                />

                <select
                  value={generateType}
                  onChange={(e) => setGenerateType(e.target.value)}
                  className="input text-sm"
                >
                  <option value="general">General</option>
                  <option value="welcome">Welcome Email</option>
                  <option value="follow-up">Follow-up</option>
                  <option value="nurture">Nurture Campaign</option>
                  <option value="promotion">Promotional</option>
                </select>

                <select
                  value={generateContext.tone}
                  onChange={(e) => setGenerateContext({ ...generateContext, tone: e.target.value })}
                  className="input text-sm"
                >
                  <option value="professional">Professional</option>
                  <option value="friendly">Friendly</option>
                  <option value="casual">Casual</option>
                  <option value="formal">Formal</option>
                </select>

                <button
                  onClick={handleGenerateTemplate}
                  disabled={loading}
                  className="w-full btn-primary"
                >
                  {loading ? 'Generating...' : '✨ Generate Template'}
                </button>
              </div>
            )}

            {/* Subject Variants */}
            {aiMode === 'variants' && (
              <div className="space-y-2">
                <button
                  onClick={() => {
                    setAiMode(null);
                    setSubjectVariants([]);
                  }}
                  className="text-sm text-gray-600 hover:text-gray-900"
                >
                  ← Back
                </button>

                {loading && <p className="text-sm text-gray-600">Generating variants...</p>}

                {subjectVariants.length > 0 && (
                  <div className="space-y-2 max-h-64 overflow-y-auto">
                    {subjectVariants.map((variant, idx) => (
                      <div
                        key={idx}
                        className="p-2 border rounded hover:bg-gray-50 cursor-pointer"
                        onClick={() => applySubjectVariant(variant)}
                      >
                        <div className="text-sm font-medium">{variant.subject}</div>
                        <div className="text-xs text-gray-600">
                          Strategy: {variant.strategy} • Est. open rate: {variant.estimated_open_rate}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Personalization Suggestions */}
            {aiMode === 'suggest' && (
              <div className="space-y-2">
                <button
                  onClick={() => {
                    setAiMode(null);
                    setPersonalizationSuggestions([]);
                  }}
                  className="text-sm text-gray-600 hover:text-gray-900"
                >
                  ← Back
                </button>

                {loading && <p className="text-sm text-gray-600">Analyzing content...</p>}

                {personalizationSuggestions.length > 0 && (
                  <div className="space-y-2 max-h-64 overflow-y-auto">
                    {personalizationSuggestions.map((suggestion, idx) => (
                      <div key={idx} className="p-2 border rounded bg-yellow-50">
                        <div className="text-sm font-medium text-yellow-900">
                          {'{{'}{suggestion.variable}{'}}'}
                        </div>
                        <div className="text-xs text-gray-700 mt-1">
                          {suggestion.reason}
                        </div>
                        <div className="text-xs text-gray-600 mt-1 font-mono">
                          Example: {suggestion.example}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default EmailAiToolbar;

